### ISSUE TITLE
请问 dnsmasq 的 IP 过滤功能有什么作用？

### ISSUE THREAD

**Issue by kuoruan** [981213/lede_src#1]
我添加此功能之后 https://github.com/981213/lede_src/commit/7c024eab3a5e41ca4a409954e89b5d4a32a581e6，编译 dnsmasq-full，发现不支持 ipset=/google.com/ss_spec_dst_fw 这种配置了，
不清楚是不是这个功能造成的。

**Comment by 981213** [comment]
这个功能就是ChinaDNS的那个chnroute，不想多加一个程序转一遍于是直接加进dnsmasq了
ipset那个问题和这个应该没啥关系

**Comment by kuoruan** [comment]
也就是说可以直接填写 chnroute 的文件吧？

```启用此功能后，当回复的结果在该列表内时，使用来自在列表内的DNS服务器返回的结果，否则使用列表外DNS服务器所返回的结果。```

这句话有点绕，假定我设置了多个 dns server，然后开启 all-servers ，查询 dns 的时候，如果一个 server 返回的地址在列表之内，一个 server 返回的地址在列表之外，那么使用列表之内这个ip，是这个意思吗？

**Comment by 981213** [comment]
这个功能就是从ChinaDNS里抄过来的chnroute功能，传进去的也就是那个chnroute文件。
我承认这个说明很绕。。。
这个东西是为了实现仅采用国外DNS返回的国外IP，避免从国内DNS查询到的受污染的结果
也就向两个DNS查询（一个IP在列表内，一个在列表外），得到的IP如果在IP列表之外，那么使用来自列表之外的那个服务器所返回的结果

但是这玩意儿本身并不带防DNS污染的功能所以那个在列表之外的DNS服务器必须保证不会被污染（比如使用ss-tunnel代理）
