### ISSUE TITLE
请教：网件3800编译时如何修改可以让面板上WIFI按键使能。

### ISSUE THREAD

**Issue by zshwq5** [981213/lede_src#2]
请教：网件3800编译时如何修改可以让面板上WIFI按键使能。

在恩山论坛原来您的帖子中看到过已经修复过网件3800,现在没有机会再看原帖了，请百忙中能否告诉修改方法。

感谢！

**Comment by 981213** [comment]
https://github.com/981213/openwrt/commit/5b57be1b68caf714273d57215a8516000e2caa04#diff-7d42b206b7e4f8c8ec6e1bc320326df6
