### ISSUE TITLE
请问 layer7 和 nDPI 哪个比较好？

### ISSUE THREAD

**Issue by kuoruan** [981213/lede_src#6]
我发现你代码中的 qos_guoguo 同 nDPI 替换了 layer7 ，不知道是出于什么考虑的？

**Comment by 981213** [comment]
听说nDPI识别比L7准就蛮换掉了，具体倒是没有比较过

**Comment by kuoruan** [comment]
本来准备移植 layer7 到 LEDE，发现了这个 nDPI，再一看，原来你这里早就实现好了。
在你这里学到了很多，感谢！
