### ISSUE TITLE
请教一下 QCA 驱动的问题

### ISSUE THREAD

**Issue by kuoruan** [981213/lede_src#7]
我现在有个 R7800，IPQ8065 + QCA9984。Lede 官方的驱动太烂了，想起以前恩山有个 QCA 驱动，不知道那个驱动是否适合我的路由器？
另我看你这里有两个 commit 1318208db5c4d2a39628fcf21741609b77bd6f07 和 23f3fce2106714ff9973de0376dafd8e2ae85682
请问这两个 commit 是用于添加 QCA 驱动支持的吗？怎么每看到 qca-wifi-perf-10.2 这个包？

**Comment by 981213** [comment]
你要是看到了这个包那就要有人吃罚单了(虽然不是我…)
你的路由至少要qcawifi 10.4才能用，恩山上目前泄露过的只有10.2版

**Comment by kuoruan** [comment]
感谢，看来我只有从官方 GPL 二进制文件移植试试了，虽然不知道能不能成功。

**Comment by 981213** [comment]
肯定会失败，因为内核版本不同。移植的时候驱动里一些函数都要修改的。

**Comment by kuoruan** [comment]
好吧，感谢。。

**Comment by kuoruan** [comment]
不好意思，借楼问一个硬件的问题，因为我这里没有懂硬件的朋友， 只能来请教你了。
我这一个 WNDR4300 彻底成砖了，需要焊 flash 修砖，但是我不懂电路。
按照这里的修砖方法：http://www.right.com.cn/forum/forum.php?mod=viewthread&tid=170402&page=1#pid1079045
需要焊一个 10KΩ 的电阻，我实在是看不懂怎么焊。
我这里有 W25Q128FVSG 的 16M 先焊到 SOP8 上。然后这电阻是这样接么？
![1](https://user-images.githubusercontent.com/8685618/29322412-fb2f8246-820f-11e7-9023-0627c2a0ec92.png)
